---
title: "Student resources"
author: "Edoardo \"Dado\" Marcora"
---

## The status quo

-   [Mindless statistics](https://www.sciencedirect.com/science/article/pii/S1053535704000927) and [Fisher, Neyman-Pearson or NHST? A tutorial for teaching data testing](https://www.frontiersin.org/articles/10.3389/fpsyg.2015.00223/full) (journal articles)
-   [Bernoulli's fallacy](https://cup.columbia.edu/book/bernoullis-fallacy/9780231199957) (book)
-   [Détente: A Practical Understanding of *P* values and Bayesian Posterior Probabilities](https://ascpt.onlinelibrary.wiley.com/doi/10.1002/cpt.2004) (journal article)

## Data science

-   [The Art of Data Science](https://bookdown.org/rdpeng/artofdatascience/) (book)
-   [R for Data Science](https://r4ds.had.co.nz/) (book)

## Probability theory

-   [Introduction to Probability](http://athenasc.com/probbook.html) (book) + [companion MIT online course](https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/) or [companion edX online course](https://www.edx.org/course/probability-the-science-of-uncertainty-and-data)

## Statistics/Frequentist inference

-   [**Statistical Thinking for the 21st Century**](https://statsthinking21.github.io/statsthinking21-core-site/) + [R companion](https://statsthinking21.github.io/statsthinking21-R-site/) (book)

-   [Introduction to Modern Statistics](https://openintro-ims.netlify.app/) (book)

## Bayesian inference

-   [Doing Bayesian Data Analysis](https://sites.google.com/site/doingbayesiandataanalysis/) (book, also available [here](https://www.sciencedirect.com/book/9780124058880/doing-bayesian-data-analysis))

-   [Bayesian data analysis for newcomers](https://link.springer.com/article/10.3758/s13423-017-1272-1) (journal article)

-   [Statistical Rethinking](https://xcelab.net/rm/statistical-rethinking/) (book) + [companion R package](https://github.com/rmcelreath/rethinking)

    -   [Statistical Rethinking 2022](https://youtube.com/playlist?list=PLDcUM9US4XdMROZ57-OIRtIK0aOynbgZN) (online course)

    -   [Bayesian inference is just counting](https://youtu.be/_NEMHM1wDfI) (one video lecture version of course above)

    -   [Science Before Statistics: Causal Inference](https://youtu.be/KNPYUVmY3NM) (video lecture by same author about causal inference)

-   [Bayesian statistics and modelling](https://www.nature.com/articles/s43586-020-00001-2) (journal article)

-   [Bayesian Analysis Reporting Guidelines](https://www.nature.com/articles/s41562-021-01177-7) (journal article)

-   [Application of Bayesian approaches in drug development: starting a virtuous cycle](https://www.nature.com/articles/s41573-023-00638-0) (journal article)

## Biostatistics

-   [**Applied Statistics for Experimental Biology**](https://www.middleprofessor.com/files/applied-biostatistics_bookdown/_book/) (book)

-   [Modern Statistics for Modern Biology](https://www.huber.embl.de/msmb/) (book)
